version: '3.9'

services:
  task-service:
    image: taskserviceapplication:latest
    ports:
      - "8080:8080"
    networks:
      - my_network

  project-service:
    image: projectserviceapplication:latest
    ports:
      - "8081:8081"
    networks:
      - my_network
  notification-service:
    image: notificationserviceapplication:latest
    ports:
      - "8082:8082"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

