name: CI/CD Pipeline for Task Service

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Package with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t task-service-image .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Push Docker Image
        run: |
          docker tag task-service-image ${{secrets.DOCKER_USERNAME}}/task_service_image:latest \
          && docker push ${{secrets.DOCKER_USERNAME}}/task_service_image:latest
